server:
  port: 8089
  servlet:
    context-path: /api/profile
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG
management:
  server:
    port: 8189
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    default-schema: profile
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: profile-app
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
